### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sunnior** [bmnielsen/Stardust#1]
Hi, I run stardust in debug mode. and there is a 100% crash in enemyUnitDestroyed. 

```
void enemyUnitDestroyed(const Unit &unit)
{
            if (unit->type.isBuilding())
            {
                Log::Get() << "Enemy destroyed: " << *unit;
            }
            unitDestroyed(unit);

            enemyUnits.erase(unit);
            unitIdToEnemyUnit.erase(unit->id);
            enemyUnitsByType[unit->type].erase(unit);
 }
```

after unitIdToEnemyUnit.erase(unit-id)
unit (which is a sharedptr) became invalid. 
I think it's because unit come from unitIdToEnemyUnit. after unitIdToEnemyUnit erases unit, in debug mode, the container will also reset the memory of the erased element. In release mode, this crash may not happen frequently.

There are also other warnings are triggerred.

```
trackEnemyUnitTimings(unit, it == unitIdToEnemyUnit.end());
```
this line, the comparation will trigger a warning, because unitIdToEnemyUnit erased an element, and the end() will return a different value.

**Comment by bmnielsen** [comment]
That's interesting. `Unit` is a `shared_ptr`, but it's being passed by reference, so I guess it is possible that erasing it from one of the maps could cause it to be freed. I've never seen it in my environment though (using clang on Mac). Which compiler are you using?

If you change the parameter in the method from `const Unit &unit` to `Unit unit`, does it resolve the crash?

I've refactored the second thing to avoid comparing with the end of the map after it has been updated.

**Comment by sunnior** [comment]
I'm using Visual Studio 2019 (v142). 

> If you change the parameter in the method from const Unit &unit to Unit unit, does it resolve the crash?

yes, this can resolve the crash.

**Comment by bmnielsen** [comment]
Cool, I'll implement that then.

If you need it, here's what the relevant section looks like after fixing the second thing you mentioned:

```
            // Create or update
            auto it = unitIdToEnemyUnit.find(bwapiUnit->getID());
            bool morphed = false;
            if (it != unitIdToEnemyUnit.end())
            {
                // If the type is still the same, update and continue
                if (it->second->type == bwapiUnit->getType())
                {
                    it->second->update(bwapiUnit);
                    continue;
                }

                // The unit has morphed - for simplicity consider the old one as destroyed and the new one created
                morphed = true;
                enemyUnitDestroyed(it->second);
            }

            auto unit = std::make_shared<UnitImpl>(bwapiUnit);
            unit->created();
            enemyUnits.insert(unit);
            unitIdToEnemyUnit.emplace(unit->id, unit);

            unitCreated(unit);

            enemyUnitsByType[unit->type].insert(unit);
            trackEnemyUnitTimings(unit, !morphed);
```

Thanks for the reports!
